"""added dislikes

Revision ID: 56db1f2c4fa4
Revises: 1bb40ece001c
Create Date: 2024-11-25 11:24:58.258350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56db1f2c4fa4'
down_revision: Union[str, None] = '1bb40ece001c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('dislike', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'dislike')
    # ### end Alembic commands ###
