"""added point

Revision ID: d5ccd7ee4f3c
Revises: e95aed705249
Create Date: 2024-12-04 17:41:43.774944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ccd7ee4f3c'
down_revision: Union[str, None] = 'e95aed705249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_points')
    # ### end Alembic commands ###
